#!/usr/bin/env node
/**
 * Live end-to-end check against the real Gemini API.
 *
 *   npm run check:gemini            uses generated placeholder references
 *   npm run check:gemini -- a.jpg gown.jpg hood.jpg cap.jpg
 *
 * Sends four references through the same code path the web app uses and writes
 * the generated image to ./check-output.png. Requires GEMINI_API_KEY in .env.
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';

import { config } from '../server/config.js';
import { generateVirtualOutfit } from '../server/generate.js';
import { validateImage } from '../server/validate.js';

const SLOTS = ['person', 'gown', 'hood', 'cap'];

/* -- placeholder references, used when no files are supplied on the CLI ---- */
function crc32(buf) {
  let c;
  let crc = 0xffffffff;
  for (let n = 0; n < buf.length; n += 1) {
    c = (crc ^ buf[n]) & 0xff;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    crc = c ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const typed = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typed));
  return Buffer.concat([length, typed, crc]);
}

function makePng(width, height, paint) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 2;

  const raw = Buffer.alloc(height * (1 + width * 3));
  let offset = 0;
  for (let y = 0; y < height; y += 1) {
    raw[offset] = 0;
    offset += 1;
    for (let x = 0; x < width; x += 1) {
      const [r, g, b] = paint(x, y);
      raw[offset] = r;
      raw[offset + 1] = g;
      raw[offset + 2] = b;
      offset += 3;
    }
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const PLACEHOLDERS = {
  person: () => makePng(640, 800, (x, y) => {
    const head = Math.hypot(x - 320, y - 240) < 110;
    return head ? [214, 178, 150] : [232, 228, 220];
  }),
  gown: () => makePng(600, 600, (x, y) => [30 + ((x + y) % 16), 44, 86]),
  hood: () => makePng(600, 600, (x, y) => [150, 40 + ((x * y) % 30), 50]),
  cap: () => makePng(600, 600, (x, y) => [24, 26 + (x % 12), 40]),
};

function loadReferences(files) {
  return SLOTS.map((slot, index) => {
    const file = files[index];
    const buffer = file ? fs.readFileSync(path.resolve(file)) : PLACEHOLDERS[slot]();
    const mime = file ? mimeFor(file) : 'image/png';
    const source = file ? path.basename(file) : 'placeholder';

    const validated = validateImage(`data:${mime};base64,${buffer.toString('base64')}`, slot, slot);
    console.log(
      `  ${slot.padEnd(7)} ${source.padEnd(28)} ${validated.mimeType} ` +
        `${validated.width ?? '?'}×${validated.height ?? '?'} ` +
        `${(validated.bytes / 1024).toFixed(0)} KB`
    );
    return validated;
  });
}

function mimeFor(file) {
  const ext = path.extname(file).toLowerCase();
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return 'image/jpeg';
}

/* ------------------------------------------------------------------ run --- */

const files = process.argv.slice(2);

console.log('\nAtelier — live Gemini check\n');
console.log(`  chain    : ${config.chain.join(' → ')}`);
console.log(`  model    : ${config.providers.gemini.model}`);
console.log(`  fallbacks: ${config.providers.gemini.models.slice(1).join(', ')}`);
console.log(`  endpoint : ${config.providers.gemini.apiBase}\n`);

if (config.isDemo) {
  console.error('  ✗ No provider credential found.');
  console.error('    Set GEMINI_API_KEY in .env — get a free key at');
  console.error('    https://aistudio.google.com/apikey\n');
  process.exit(1);
}

console.log('  references:');
const references = loadReferences(files);
console.log('');

const startedAt = Date.now();

try {
  const result = await generateVirtualOutfit({
    person: references[0],
    pieces: references.slice(1),
  });

  const extension = (result.mimeType.split('/')[1] || 'png').replace('jpeg', 'jpg');
  const output = path.join(config.rootDir, `check-output.${extension}`);
  fs.writeFileSync(output, Buffer.from(result.base64, 'base64'));

  const bytes = Buffer.byteLength(result.base64, 'base64');

  console.log(`  ✓ generated by ${result.provider} (${result.model})`);
  if (result.attempts.length) console.log(`    after: ${result.attempts.join('; ')}`);
  console.log(`    ${result.mimeType}, ${(bytes / 1024).toFixed(0)} KB, ${Date.now() - startedAt} ms`);
  console.log(`    written to ${output}\n`);

  if (result.demo) {
    console.log('  ⚠ This is the demo asset, not a real generation.\n');
    process.exit(1);
  }
} catch (error) {
  console.error(`  ✗ generation failed after ${Date.now() - startedAt} ms\n`);
  console.error(`${error.message}\n`);
  process.exit(1);
}
